spring:
  profiles:
    active: ${APP_PROFILE:test}
  server:
    port: 80

  jpa:
    open-in-view: false

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 360000

# test
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
